name: workflow1
on: 
 push:
  branches:
    - main
 workflow_dispatch:
env:
  name: jass
jobs:
  my-jobs:
   runs-on: ubuntu-latest
   env:
     display: pwd

  
   steps:
    - name: env-1
      run: echo "print ${{ env.name }}"
    - name: print the working-directory
      run: pwd && date && whoami
    - name: env-1
      env:
        dd: date
      run: echo "print ${{ env.dd }}" 
